# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170515_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='An',
        ),
    ]
