# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170515_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='An',
        ),
    ]
